//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWithNinject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lease
    {
        public Lease()
        {
            this.tenants = new HashSet<tenant>();
        }
    
        public int LeaseId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tenant> tenants { get; set; }
    }
}
