//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWithNinject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public tenant()
        {
            this.Leases = new HashSet<Lease>();
        }
    
        public int tentId { get; set; }
        public string tname { get; set; }
    
        public virtual ICollection<Lease> Leases { get; set; }
    }
}
