//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWithNinject.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Unit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitAddress { get; set; }
    }
}
